
{
    # env_py2 is a bit of a hack so that python2 scripts can be called
    # by snakemake (which is written in python3). The value should set
    # PATH environment variable that is suitable for running python2
    "env_py2" : "PATH=/iblm/netapp/home/gmcvicker/anaconda2/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin;",

    # WASP directory (should have trailing '/')
    "wasp_dir" : "/iblm/netapp/home/gmcvicker/proj/WASP",


    # directory to write data files to
    "base_dir" : "/iblm/netapp/home/gmcvicker/proj/WASP/CHT/nick_input_data_chr22",

    # minimum number of allele-specific reads (combined across individuals)
    # required to perform combined test on a region
    "min_as_count" : "10",

    # location of chromInfo file (can be downloaded from UCSC genome browser)
    "chrom_info" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/chromInfo.hg19.txt",

    # directory containing impute or VCF SNP files
    "snp_dir" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/genotypes",
    # file containing identifiers for impute or VCF SNP file
    "snp_samples" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/genotypes/YRI_samples.txt",

    # directory containing genome fasta files, one per chromosome
    "fasta_dir" : "/iblm/netapp/data1/external/GRC37/chroms",


    # text file containing identifiers of samples used in study (one per line)
    "samples_file" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/H3K27ac/samples.txt",

    # directory containing BAM files
    "bam_dir" : "/iblm/netapp/home/gmcvicker/proj/WASP/examples/example_data/H3K27ac"

    # postfix of BAM files
    "bam_postfix" : ".keep.rmdup.bam"
    
    

}
